### ISSUE TITLE
 是否考虑适配新版本的钉钉？

### ISSUE THREAD

**Issue by zzexnn** [HolmesZhao/MacOSDingTalkRevoke#2]
大佬是否考虑适配 7.6.10 的钉钉？另外想问一下，M 系列的芯片可以用吗？

**Comment by songxing10000** [comment]
要是能屏蔽已读接口就爽了啊

**Comment by HolmesZhao** [comment]
> 大佬是否考虑适配 7.6.10 的钉钉？另外想问一下，M 系列的芯片可以用吗？

我只有 M 的😂, 7.6.10 没差多少版本, 不想搞🤣浪费时间

**Comment by HolmesZhao** [comment]
> 要是能屏蔽已读接口就爽了啊

不会啊🤣我这也是抄别人的

**Comment by OwnerCM** [comment]
我也是手欠升级了7.6.10，看来只能回退了

**Comment by songxing10000** [comment]
我找到了个关键点，把wkwebview执行js那个方法hook为空，就不会发送已读了，但是聊天页面也变成空的了，可能还需要过滤下，让一些js可以执行

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: OwnerCM ***@***.***>
发送时间: Tuesday, August 27, 2024 1:57:00 PM
收件人: HolmesZhao/MacOSDingTalkRevoke ***@***.***>
抄送: xingsong ***@***.***>; Comment ***@***.***>
主题: Re: [HolmesZhao/MacOSDingTalkRevoke] 是否考虑适配新版本的钉钉？ (Issue #2)


我也是手欠升级了7.6.10，看来只能回退了

―

**Comment by OwnerCM** [comment]
> > 大佬是否考虑适配 7.6.10 的钉钉？另外想问一下，M 系列的芯片可以用吗？
> 
> 我只有 M 的😂, 7.6.10 没差多少版本, 不想搞🤣浪费时间

@HolmesZhao  我修改代码兼容7.6.10，已经提交Pull Request，大佬抽空可以合并一下。

**Comment by zzexnn** [comment]
> > > 大佬是否考虑适配 7.6.10 的钉钉？另外想问一下，M 系列的芯片可以用吗？
> > 
> > 
> > 我只有 M 的😂, 7.6.10 没差多少版本, 不想搞🤣浪费时间
> 
> @HolmesZhao 我修改代码兼容7.6.10，已经提交Pull Request，大佬抽空可以合并一下。

大佬 nb，感谢付出！

**Comment by songxing10000** [comment]
已经实现7.6.0版本的屏蔽已读功能

**Comment by HolmesZhao** [comment]
> > > 大佬是否考虑适配 7.6.10 的钉钉？另外想问一下，M 系列的芯片可以用吗？
> > 
> > 
> > 我只有 M 的😂, 7.6.10 没差多少版本, 不想搞🤣浪费时间
> 
> @HolmesZhao 我修改代码兼容7.6.10，已经提交Pull Request，大佬抽空可以合并一下。

大佬 nb，感谢付出！, 我现在合并一下, 之前没看到 @OwnerCM

**Comment by songxing10000** [comment]
屏蔽消息已读功能已好使，只不过是修改二进制的方式实现的

**Comment by HolmesZhao** [comment]
> 屏蔽消息已读功能已好使，只不过是修改二进制的方式实现的

@songxing10000 用 hopper 直接改的macho?

**Comment by songxing10000** [comment]
是的

**Comment by HolmesZhao** [comment]
> 是的

居然是 hopper 付费用户, 流弊🤣

**Comment by songxing10000** [comment]
有破解版啊

**Comment by HolmesZhao** [comment]
> 有破解版啊

现在 Silicon 的也有吗?

**Comment by songxing10000** [comment]
> > 有破解版啊
> 
> 
> 
> 现在 Silicon 的也有吗?

有，ida也有

**Comment by HolmesZhao** [comment]
> > > 有破解版啊
> > 
> > 
> > 现在 Silicon 的也有吗?
> 
> 有

求链接😁

**Comment by HolmesZhao** [comment]
> 有破解版啊

![image](https://github.com/user-attachments/assets/06fc4ab4-13d3-48e0-8a98-75bbaae1c1bc)
完美啊, 才发现 out 了
