### ISSUE TITLE
替换运行成功，撤回消息展示无变化

### ISSUE THREAD

**Issue by metallica8023** [HolmesZhao/MacOSDingTalkRevoke#7]
钉钉版本：7.6.10
Mac 版本：Sequoia 15.1 Beta

文件替换后撤回消息无变化，功能无变化。

**Comment by kts-kris** [comment]
同样的版本和系统，显示替换成功了，但是没有效果

**Comment by HolmesZhao** [comment]
好像真的诶🤣7.6.16 也是, 搞不懂🤣先用旧的吧

**Comment by kts-kris** [comment]
7.6.10 在 Mac 版本：Sequoia 15.1 Beta 下，似乎也是没有效果

**Comment by GengJian** [comment]
> 7.6.10 在 Mac 版本：Sequoia 15.1 Beta 下，似乎也是没有效果

先把钉钉降到```7.6.0```旧版本稳的一批

**Comment by kts-kris** [comment]
7.6.0 果然稳的一批，一起看看怎么支持新版本？

**Comment by HolmesZhao** [comment]
尝试删除 chatbox 那个 js 居然都不影响使用....以前在 UI 上就看不到任何东西了....我用非 15.1 系统, 7.6.16 都是可以的

**Comment by kts-kris** [comment]
> 尝试删除 chatbox 那个 js 居然都不影响使用....以前在 UI 上就看不到任何东西了....我用非 15.1 系统, 7.6.16 都是可以的

所以可能是beta系统有沙盒？有人是正式版的 15 系统吗？可以试试正式版是不是就不存在沙盒问题。

**Comment by HolmesZhao** [comment]
> > 尝试删除 chatbox 那个 js 居然都不影响使用....以前在 UI 上就看不到任何东西了....我用非 15.1 系统, 7.6.16 都是可以的
> 
> 所以可能是beta系统有沙盒？有人是正式版的 15 系统吗？可以试试正式版是不是就不存在沙盒问题。

15.1 也已经正式了吧

**Comment by kts-kris** [comment]
macOS：15.2 Beta (24C5073e)
钉钉：7.6.25（41241063）
防撤回功能正常，未出现沙盒情况。真诡异

**Comment by HolmesZhao** [comment]
有毒, 15.2 beta 确实恢复正常了, 建议用清理工具清理干净钉钉的内容然后再跑这个脚本, 不然有缓存可能还是不成功的

**Comment by Zane-Zzx** [comment]
> 有毒, 15.2 beta 确实恢复正常了, 建议用清理工具清理干净钉钉的内容然后再跑这个脚本, 不然有缓存可能还是不成功的

请问用啥清理工具，我15.1撤回无效果

**Comment by HolmesZhao** [comment]
> > 有毒, 15.2 beta 确实恢复正常了, 建议用清理工具清理干净钉钉的内容然后再跑这个脚本, 不然有缓存可能还是不成功的
> 
> 请问用啥清理工具，我15.1撤回无效果

15.1 不知道为啥就是有问题, 15.2 可以用, 就不想研究 15.1 了😂, 清理工具用的是
![image](https://github.com/user-attachments/assets/ac349cd6-ffe2-4b60-aaa7-e763afbb06b7)

**Comment by OwnerCM** [comment]
> > > 有毒, 15.2 beta 确实恢复正常了, 建议用清理工具清理干净钉钉的内容然后再跑这个脚本, 不然有缓存可能还是不成功的
> > 
> > 
> > 请问用啥清理工具，我15.1撤回无效果
> 
> 15.1 不知道为啥就是有问题, 15.2 可以用, 就不想研究 15.1 了😂, 清理工具用的是 ![image](https://private-user-images.githubusercontent.com/19728934/387895231-ac349cd6-ffe2-4b60-aaa7-e763afbb06b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzE0ODYsIm5iZiI6MTczMjY3MTE4NiwicGF0aCI6Ii8xOTcyODkzNC8zODc4OTUyMzEtYWMzNDljZDYtZmZlMi00YjYwLWFhYTctZTc2M2FmYmIwNmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAxMzMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NGI0ZjI0MGUwNzUxYTMyNDJiNWZmZGZiZmFhOGU0Y2E2NmRlODM4NWE5Y2IxYTdlMWE0NjcyYzc2NzE1NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.quwnRo4EG5-KoNolD986b5cV6nVCfSHdphQ1jassLW0)

经测试升级到15.2 beta3依旧无法使用，可能和系统无关。请问你是使用清理工具重新运行脚本就正常了吗？

**Comment by OwnerCM** [comment]
> > > 有毒, 15.2 beta 确实恢复正常了, 建议用清理工具清理干净钉钉的内容然后再跑这个脚本, 不然有缓存可能还是不成功的
> > 
> > 
> > 请问用啥清理工具，我15.1撤回无效果
> 
> 15.1 不知道为啥就是有问题, 15.2 可以用, 就不想研究 15.1 了😂, 清理工具用的是 

经过验证并非缓存的问题，首次清理缓存后第一次使用钉钉是正常的，但是钉钉应该会再次生成缓存，下次使用的时候会优先调用缓存导致防撤回再次失效。暂时还没找到调用缓存的地址

**Comment by zzexnn** [comment]
> > > > 有毒，15.2 beta 确实恢复正常了，建议用清理工具清理干净钉钉的内容然后再跑这个脚本，不然有缓存可能还是不成功的
> > > 
> > > 
> > > 请问用啥清理工具，我 15.1 撤回无效果
> > 
> > 
> > 15.1 不知道为啥就是有问题，15.2 可以用，就不想研究 15.1 了😂, 清理工具用的是
> 
> 经过验证并非缓存的问题，首次清理缓存后第一次使用钉钉是正常的，但是钉钉应该会再次生成缓存，下次使用的时候会优先调用缓存导致防撤回再次失效。暂时还没找到调用缓存的地址

我的 15.1.1 的系统，M3 pro，同样出现了类似的问题，显示替换成功，但是没有效果。而且我之前用的是 7.6.10 版本的，之前一直正常，就是最近突然不能用了，我也没有更新。
盲猜是不是钉钉热更新了什么东西？

**Comment by OwnerCM** [comment]
> > > > > 有毒，15.2 beta 确实恢复正常了，建议用清理工具清理干净钉钉的内容然后再跑这个脚本，不然有缓存可能还是不成功的
> > > > 
> > > > 
> > > > 请问用啥清理工具，我 15.1 撤回无效果
> > > 
> > > 
> > > 15.1 不知道为啥就是有问题，15.2 可以用，就不想研究 15.1 了😂, 清理工具用的是
> > 
> > 
> > 经过验证并非缓存的问题，首次清理缓存后第一次使用钉钉是正常的，但是钉钉应该会再次生成缓存，下次使用的时候会优先调用缓存导致防撤回再次失效。暂时还没找到调用缓存的地址
> 
> 我的 15.1.1 的系统，M3 pro，同样出现了类似的问题，显示替换成功，但是没有效果。而且我之前用的是 7.6.10 版本的，之前一直正常，就是最近突然不能用了，我也没有更新。 盲猜是不是钉钉热更新了什么东西？

是的，我也是没升级钉钉，突然不可用的。目前能确定的是js文件替换没有问题，因为清除缓存以后会生效一段时间，但是不知道是钉钉还是mac 15会自动缓存导致不引用chatbox那个js文件。

**Comment by OwnerCM** [comment]
> 有毒, 15.2 beta 确实恢复正常了, 建议用清理工具清理干净钉钉的内容然后再跑这个脚本, 不然有缓存可能还是不成功的

退回7.6.0版本后恢复正常，看来的确是版本及后端推送更新的问题
