### ISSUE TITLE
7.6.25 41241063没有成功

### ISSUE THREAD

**Issue by request101** [HolmesZhao/MacOSDingTalkRevoke#9]

**Comment by bbingz** [comment]
一样，没有成功。

**Comment by OwnerCM** [comment]
退回7.6.0版本

**Comment by HolmesZhao** [comment]
![image](https://github.com/user-attachments/assets/cd0df2d1-e8c7-4456-882e-7788372a0f89)
用这个清理一下, 然后再试试呢, 我这边 M3 + macOS 15.2 是没问题的

**Comment by moosetk** [comment]
本地已安装7.6.35版本钉钉
选中的版本暂未支持
简单地把 25 改成 35 就可以了吗？

**Comment by HolmesZhao** [comment]
> 本地已安装7.6.35版本钉钉 选中的版本暂未支持 简单地把 25 改成 35 就可以了吗？

@moosetk 不行, 要改代码
